# Generated by Django 4.2.7 on 2023-12-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keep_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='session_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
