# Generated by Django 4.2.7 on 2023-12-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_keep_logged_in_user_session_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='keep_logged_in',
        ),
    ]
