# Generated by Django 5.0.3 on 2024-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_keep_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('session_key', models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
                ('inactive_count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_expire_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='session_key',
        ),
    ]
