# Generated by Django 5.0.3 on 2024-07-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customsession_remove_user_session_expire_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.BooleanField(default=False)),
                ('field2', models.BooleanField(default=False)),
            ],
        ),
    ]
