# Generated by Django 5.0.3 on 2024-08-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
