# Generated by Django 5.0 on 2025-02-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0002_order_mobile_number_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=200, unique=True)),
                ('amount', models.FloatField()),
                ('amount_due', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=10)),
                ('entity', models.CharField(max_length=30)),
                ('offer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt', models.CharField(max_length=50)),
                ('note_1', models.CharField(max_length=250)),
                ('note_2', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_timestamp', models.DateTimeField(null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.order')),
            ],
        ),
    ]
