# Generated by Django 5.0 on 2025-07-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='razorpay_order_id',
            new_name='cachefree_order_id',
        ),
    ]
