# Generated by Django 5.0 on 2025-07-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_razorpay_to_cachefree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cachefree_order_id',
            new_name='razorpay_order_id',
        ),
    ]
